project:
  type: website

website:
  title: "R-ArcGIS Bridge"
  page-footer:
    center: "As a member of the R Consortium, Esri is part of the R community and supports the R project."
    right:
      - icon: github
        href: https://github.com/r-arcgis
      - icon: globe
        href: https://esri.com

  sidebar:
    style: "floating"
    contents:
      - href: index.qmd
        text: Home
      - section: ArcGIS Pro
        contents:
          - arcgisbinding/installing-arcgisbinding.qmd
          - geoprocessing-tools.qmd
      - section: Location Services
        contents:
          - location-services/connecting-to-a-portal.qmd
          - location-services/read-data.qmd
      - tutorials.qmd
      - workflows.qmd
      - packages.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



highlight-style: pygments