project:
  type: website

website:
  title: "R-ArcGIS Bridge"
  repo-url: https://github.com/r-arcgis/r-bridge-site
  repo-actions: [edit, issue]
  page-footer:
    center: "As a member of the R Consortium, Esri is part of the R community and supports the R project."
    right:
      - icon: github
        href: https://github.com/r-arcgis
      - icon: globe
        href: https://esri.com

  sidebar:
    style: "floating"
    contents:
      - href: index.qmd
        text: Home
      - section: ArcGIS Pro
        contents:
          - arcgisbinding/installing-arcgisbinding.qmd
          - geoprocessing-tools.qmd
      - section: Location Services
        contents:
          - location-services/overview.qmd
          - location-services/connecting-to-a-portal.qmd
          - location-services/read-data.qmd
          - location-services/publishing.qmd
          - location-services/workflows/add-delete-update.qmd
          - location-services/workflows/overwrite-feature-service.qmd
          - section: Tutorials
            contents:
              - location-services/tutorials/shiny-dash/index.qmd
      - packages.qmd
      - resources.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-link: false


highlight-style: pygments