project:
  type: website

website:
  title: "R-ArcGIS Bridge"
  navbar:
    right:
      - href: index.qmd
        text: Home
  sidebar:
    style: "docked"
    contents:
      - href: index.qmd
        text: Home
      - text: Packages
        href: packages.qmd
      - geoprocessing-tools.qmd
      - tutorials.qmd
      - workflows.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



highlight-style: pygments