project:
  type: website

website:
  title: "R-ArcGIS Bridge"
  repo-url: https://github.com/r-arcgis/r-bridge-site
  repo-actions: [edit, issue]
  page-footer:
    center: "As a member of the R Consortium, Esri is part of the R community and supports the R project."
    right:
      - icon: github
        href: https://github.com/r-arcgis
      - icon: globe
        href: https://esri.com

  sidebar:
    collapse-level: 1
    style: "floating"
    contents:
      - href: index.qmd
        text: Overview
      - text: Key Features
      - docs/get-started.qmd
      - docs/installation.qmd
      - section: Authentication
        contents:
          - text: "Overview"
            href: docs/auth
          - docs/auth/storing-credentials.qmd
          - href: location-services/connecting-to-a-portal.qmd
            text: "Authenticating with R"
      - section: Layers
        contents:
        - text: "Overview"
          href: docs/layers/overview.qmd
        - text: "Reading Feature Services"
          href: docs/layers/read-layers.qmd
        - text: "Reading Image Services"
          href: docs/layers/read-rasters.qmd
        - text: "Publishing layers"
          href: docs/layers/publishing.qmd
      - section: Editing
        contents:
        - text: "Overview"
          href: docs/editing/overview.qmd
        - text: "Adding features"
          href: docs/editing/add-features.qmd
        - docs/editing/update-features.qmd
        - docs/editing/delete-features.qmd
        - text: "Truncate and append features"
          href: docs/editing/overwrite-features.qmd
      - section: Geocoding
        contents:
        - docs/geocode/overview.qmd
        - docs/geocode/forward-geocoding.qmd
        - href: docs/geocode/bulk-geocoding.qmd
          text: "Bulk Geocoding"
        - href: docs/geocode/reverse-geocoding.qmd
          text: "Reverse Geocoding"
      - section: Places
        contents:
        - docs/places/overview.qmd
      - section: Geoprocessing
        contents:
        - docs/geoprocessing/overview.qmd
        - text: "Making Geoprocessing Tools"
          href: docs/geoprocessing/creating-gp-tools.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-link: false


highlight-style: pygments

execute:
  freeze: true