project:
  type: website

website:
  title: "R-ArcGIS Bridge"
  page-footer:
    center: "As a member of the R Consortium, Esri is part of the R community and supports the R project."
    right:
      - icon: github
        href: https://github.com/r-arcgis
      - icon: globe
        href: https://esri.com
  navbar:
    right:
      - href: index.qmd
        text: Home
  sidebar:
    style: "docked"
    contents:
      - href: index.qmd
        text: Home
      - text: Packages
        href: packages.qmd
      - arcgisbinding/installing-arcgisbinding.qmd
      - geoprocessing-tools.qmd
      - tutorials.qmd
      - workflows.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



highlight-style: pygments