---
title: Overview
---

There a number of times when you will need to verify who you say you are when using ArcGIS location services. This is done through a process called **authentication**. Authentication is required when you want to:

- access private content
- publish your own layers
- geocode addresses in bulk 
- store geocoding results in a file
- or access POI data through `{arcgisplaces}`

## Sign up for an account 

To access certain content, services, or organizations, you will need to be signed in to either an ArcGIS Developer account, ArcGIS Online account, or ArcGIS Enterprise account. The type of account, user type, and role you need depends on the resource you need to access and the operations you wish to undertake.

If you do not have an account, select one of the options below: 

- [Get started for free with ArcGIS Platform](https://www.esri.com/en-us/arcgis/products/arcgis-location-platform/overview)
- [Get a free trial of ArcGIS Online](https://www.esri.com/en-us/arcgis/products/arcgis-online/overview)

:::{.callout-tip}
To get an account for an existing ArcGIS organization contact your ArcGIS Online or ArcGIS Enterprise administrator.
:::

## Authentication functions

At a high-level, the R  package `{arcgisutils}` provides the following functions for authentication: 

- `auth_key()`: uses a developer API key
- `auth_user()`: username and password
- `auth_code()`: OAuth2 Code flow
- `auth_client()`: OAuth2 client flow
- `auth_binding()`: inherits auth from ArcGIS Pro


