---
title: System requirements
uid: system-requirements
freeze: true
--- 

## Operating System
The R-ArcGIS Bridge’s `{arcgis}` meta-package for location services supports Mac OS, Windows, and most Linux distributions.
In order to use the `{arcgisbinding}` package, you must have ArcGIS Pro ≥ 3.1 installed and licensed on a 64-bit Windows machine.

## R Version
The minimum of version of R supported is 4.1.0. However, we recommend updating your R version whenever possible to keep up with enhancements, features, and any security updates.

## Dependencies
The `{arcgis}` meta-package consists of many smaller R packages, each of these with different R package dependencies. However, all of them share a dependency on `{arcgisutils}`.

`{arcgisutils}` is built in part using Rust via [extendr](https://extendr.github.io/). We recommend installing a binary from the [R-universe](https://r-arcgis.r-universe.dev/) or CRAN.
```{r eval = FALSE}
install.packages("arcgis", repos = c("https://r-arcgis.r-universe.dev", "https://cloud.r-project.org"))
```
If you need to install from source, `rustc` must be available with a minimum version of 1.70. We encourage using the most recent version of rust.

:::{.callout-tip}
We recommend installing Rust via [`rustup`](https://rustup.rs/). If you are on Windows, you must add the Windows GNU target via `rustup target add x86_64-pc-windows-gnu`.
:::